name: Print Branch Name

on:
  push:
    branches:  # only execute the pipeline if the push is to one of the following branches
      - main
      - develop
    paths:  # only execute the pipeline if files in either of the folders change
      - '.github/workflows/**'
      - 'trigger_code/**'

jobs:
  print_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message
        run: echo "hello from ${GITHUB_REF_NAME}!!"
