name: Print Branch Name (optional tmate)

on:
  push:
    branches:  # only execute the pipeline if the push is to one of the following branches
      - main
      - develop
    paths:  # only execute the pipeline if files in either of the folders change
      - '.github/workflows/**'
      - 'trigger_code/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

concurrency:  # only allow one instance of the pipeline to run at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  print_branch_name:
    timeout-minutes: 20  # timeout the job after 20 minutes
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message
        run: echo "hello from ${GITHUB_REF_NAME}!!"
      - name: Print secrets
        run: echo "hi ${{ secrets.MYSECRET }}"
      - name: Print variable
        run: echo "hi ${{ vars.MY_VAR }}"
      - name: checkout current branch
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}