name: Deploy to Remote Server

on:
  push:
    branches:
      - main # adjust with your branch name
      - develop
    paths:  # only execute the pipeline if files in either of the folders change
      - '.github/workflows/**'
      - 'select_env_code/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  SECRET: ${{ 
    (github.ref == 'refs/heads/main') && 'production' ||
    (github.ref == 'refs/heads/develop') && 'staging' || 
    'feature'}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    # print the secret env
    - name: Print Secret
      run: echo $SECRET
      
    
