name: Set Dynamic Env

on:
  push:
    branches:
      - main # adjust with your branch name
      - develop
    paths:  # only execute the pipeline if files in either of the folders change
      - '.github/workflows/**'
      - 'select_env_code/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  SECRET: ${{ 
    (github.ref == 'refs/heads/main') && secrets.MAIN_SECRET ||
    (github.ref == 'refs/heads/develop') && secrets.DEV_SECRET || 
    'Wrong branch. No secret for you!'}}

jobs:
  show_env:
    runs-on: ubuntu-latest

    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    # print the secret env
    - name: Print Secret
      run: echo $SECRET
    
    # write the secret to a file and then print the content of it
    - name: Write Secret to File
      run: echo $SECRET > secret.txt

    - name: Print Secret from File
      run: cat secret.txt
 

    
